name: ${project.name}
main: com.crylegend.authmebridge.AuthMeBridge
version: ${project.version}
website: http://www.craftfriends.fr
author: CryLegend
description: The first AuthMe bungeecord addon
depend: [AuthMe]
